steps:
  # Run database migrations
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        npx prisma generate
        npx prisma db push
    env:
      - 'DATABASE_URL=${_DATABASE_URL}'
      - 'NODE_ENV=production'
  
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_NAME}', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_IMAGE_NAME}'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-env-vars'
      - 'DATABASE_URL=${_DATABASE_URL}'
      - '--set-env-vars'
      - 'JWT_SECRET=${_JWT_SECRET}'
      - '--set-env-vars'
      - 'NEXTAUTH_URL=${_NEXTAUTH_URL}'
      - '--set-env-vars'
      - 'NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=${PROJECT_ID}'
      - '--set-env-vars'
      - 'STORAGE_BUCKET=${_STORAGE_BUCKET}'

# Store images in Artifact Registry
images:
  - '${_IMAGE_NAME}'

# Build timeout
timeout: '1200s'

# Available substitutions
# Bu değerleri Cloud Build trigger'ında veya komut satırında ayarlayın
substitutions:
  _DATABASE_URL: 'postgresql://username:password@host:port/database'
  _JWT_SECRET: 'your-super-secret-jwt-key-here'
  _NEXTAUTH_URL: 'https://your-app-url.vercel.app'
  _NEXTAUTH_SECRET: 'your-nextauth-secret-here'
  _STORAGE_BUCKET: 'your-project-id-storage-bucket'
  _IMAGE_NAME: 'europe-west1-docker.pkg.dev/your-project-id/your-repo/your-app:latest'
  _SERVICE_NAME: 'your-service-name'
